version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: spotify
