version: '3.1'

services:

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      APP_PORT: 80
      APP_POSTGRES_STRING: postgres://admin:letmein@db/spotify

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: spotify
